version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinger
    image: pinger
    env_file:
      - .env    # loads env vars from file outside the image
    restart: unless-stopped
